### ISSUE TITLE
Escaping issues

### ISSUE THREAD

**Issue by renzo800000** [fnx-io/i69n#3]
First off, thank you for creating this awesome library. It's so much better than any other I have found!

However, I noticed that this library has some serious escaping issues. To demonstrate them, I 
created an i69n.yaml file with the following contents:

    didntWork: "That didn't work."
    didntWorkEscaped: "That didn\'t work."
    twoLineMessage: "This is line 1\nThis is line 2"

The first line fails with the following message:

    line 18, column 45: Unterminated string literal.
       ╷
    18 │     String get didntWork => 'That didn't work.';
       │                                                ^
       ╵
Ideally, the library would escape the characters for me, but manually escaping them would be ok. So, in the second line I escaped the ', which gave me the following error:

    Error on line 2, column 29: Unknown escape character.
      ╷
    2 │ didntWorkEscaped: "That didn\'t work."
      │                             ^
      ╵
So, regular escaping does not work. The only workaround is double escaping everything (' becomes \\\\'). This is far from ideal.

When you don't double-escape a newline character, the library even processes it as if it is a real newline character. The third line gave me the following error messages:

    line 19, column 45: Unterminated string literal.
       ╷
    19 │     String get twoLineMessage => 'This is line 1
       │                                                ^
       ╵

    line 20, column 16: Unterminated string literal.
       ╷
    20 │ This is line 2';
       │                ^
       ╵

The library is usable with the double-escaping workaround, however, when you try to manage a large project with a lot of translations and translators, you would have to either manually check all translations for escaping issues, or write some script to do it for you. So, it would be great if the library could handle this itself.

**Comment by Tomucha** [comment]
I will look into it and let you know. It's definitely something which needs to be solved on my side.

Give me a few days.

**Comment by Tomucha** [comment]
The fix is pushed, it's not a released package yet, I'll test it on my project and then release it.
If you want to test it as Github dependency, it would be great :-)

**Comment by renzo800000** [comment]
Thanks! Its a lot better. I'm glad it now supports social distancing :). Auto-deleting the old builds is also a great addition.

While it handles most cases ok now, it still has some problems with the functions (E.G. _plural).

I know this can't be easily fixed. You will probably always need some form of escaping there, since you are between both single and double apostrophes. 

An example of such a situation: 
`foundTasks(int count): "${_plural(count, zero: 'didn't find any tasks', one: 'found 1 task', other: 'found $count tasks')}"`

The only solutions I can think of right now are either manually (double) escaping or making the different plurals into separate messages and linking them together in 1 function. 

Do you have any ideas on how this could be improved?

**Comment by Tomucha** [comment]
I pushed an attempt to make it easier. To sum up current behavior:

- I don't escape backslash, which will make escaping by hand ... possible :-)
- I don't escape anything between ${ and } (it's not complete parser, it's quite naive, but it should work in common cases)

So in your case, you YAML should look like this - double backslash in 'dont' - double because of YAML format ...

`problematic(int count): "${_plural(count, zero:'didn\\'t find any tasks', one:'found 1 task', other: 'found $count tasks')}"
`

BTW: did the 'zero' category work for you? I found a bug there too :-/

BTW 2: Thank you very much for your time, I know you have better things to do :+1:

**Comment by renzo800000** [comment]
Yeah, already thought the double backslash would be necessary, I just hoped there was a better solution.

I did have some problems with the 'zero' category in English before but just thought it was intended behavior since in English there is no difference between the zero and multiple categories. (0 apples, 1 apple, 2 apples, etc.). I did overwrite it with a custom .registerResolver call so I could include messages like 'no apples' in the same function:

```
i69n.registerResolver("en", (count, type){
      switch(count){
        case 0: return i69n.QuantityCategory.zero;
        case 1: return i69n.QuantityCategory.one;
        case 2: return i69n.QuantityCategory.two;
      }
      return i69n.QuantityCategory.other;
    });
```

Maybe you should think about always returning the zero, one and two categories for their respective amounts, even if the language makes no difference between them. That way when using the library you have more options to play with. This would allow for messages like: 

`multiplier(int factor): "${_plural(factor, zero: 'Zero', one: 'The original amount',  two: 'Twice the original amount', other: '${factor}x the original amount')}"`

**Comment by renzo800000** [comment]
By the way, I just discovered another issue. I think it might be related to the latest push. If not, I will start a separate issue.

It seems that double interpolation with curly brackets doesn't work. For example, the message
`test(int b): "${_plural(b, other: '${b}')}"`
will generate an error while building. 

I found this problem while working with ordinals: 
`ordinalNumber(int n): "${_ordinal(n, one: '1st', two: '2nd', few: '3rd', other: '${n}th')}"`
will also fail.

For now, I'll just add a space between '$n' and 'th' so I don't have to use curly brackets:
`ordinalNumber(int n): "${_ordinal(n, one: '1st', two: '2nd', few: '3rd', other: '$n th')}"`
This seems to work. 

Please let me know if you are able to fix this.

**Comment by Tomucha** [comment]
It seems to be, that trying to be smart and escape you single quotes automatically was a mistake :-/ This will never end ... So let's try something else. I will use double quotes in generated source codes, and I will escape only special "white spaces". You should be fine in almost all cases, but you will need to do some escaping in following cases:

    problematic: "Hello \\\"world\\\"!"  
    //                  ^^^ yes, tripple backslash
    
    lessProblematic: 'Hello \"world\"!'
    //                      ^ use single quotes for YAML, add only one backslash for dart    
    
    alsoProblematic(int count): "${_plural(count, zero:'didn\\'t find any tasks', other: 'found some tasks')}"
    //                                                      ^ here

But otherwise you should be fine:

    count(int cnt): "You have created $cnt ${_plural(cnt, one:'invoice', many:'invoices')}."
    letsGo: Let's go!

**Comment by Tomucha** [comment]
You are right about the "zero" problem. I blindly followed the language specification, but your example shows that in reality you might want something more. So I added "zero" to default english (and czech) implementation of quantity resolver. There is some chain of defaults, so if you don't specify "zero" string, "other" or "many" is used.

**Comment by renzo800000** [comment]
Thanks! that seems to have solved it!

**Comment by Tomucha** [comment]
Great. I'll keep it open for a while, in a few days I'll close it and release as a package. Let me know if you run into anything else.

Thanks again!

**Comment by Tomucha** [comment]
It's out.

https://pub.dev/packages/i69n
