### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by Nazacheres** [fnx-io/i69n#4]
Hello, thank you for such an amazing library.
Could you please update the dependencies? 
Particularly YAML.

**Comment by Tomucha** [comment]
Will do, but I'm in the middle of upgrading to null safety ... have you tried to force specific YAML version in your pubspec ?

```
dependency_overrides:
  yaml: '3.1.0'
```

**Comment by Nazacheres** [comment]
Yeah, it worked for some other packages, it doesn't for this one tho, not sure why

module translations:
```dependencies:
  i69n: 1.1.0

dependency_overrides:
  yaml: 3.1.0```

main module:
```
dev_dependencies:
  yaml: 3.1.0
```

Because every version of translations from path depends on i69n 1.1.0 which depends on yaml ^2.2.0, every version of translations from path requires yaml ^2.2.0.

**Comment by Nazacheres** [comment]
Oh, just found an issue while was writing this:
as dev_dependencies != dependency_overrides, it should be:
```
dependency_overrides:
  yaml: 3.1.0
```

so yeah, overriding works, but still, I was mostly checking if its active, and will be updated anytime soon. 
Thank you.

**Comment by Tomucha** [comment]
Sure thing, this would be a workaround, expect the solution in few week.

**Comment by Tomucha** [comment]
Hi there! Please try:

```
dependencies:
  i69n: ^2.0.0-nullsafe.1
```

It should allow you to remove the dependency_override. Please let me know if it helps.
