### ISSUE TITLE
Cannot generate files for fil - Filipino Pilipino

### ISSUE THREAD

**Issue by StanislawNagorski** [fnx-io/i69n#9]
Hi! Thx for cool package!

Filipino code is 3 chars **fil**  it is not validated:
`Exception: Wrong language code fil in file name translations_fil.i69n.yaml. Language code must match RegExp: pattern=^[a-z]{2}$ flags=
`
It is supported by Flutter:
https://api.flutter.dev/flutter/flutter_localizations/GlobalMaterialLocalizations-class.html

**Comment by Tomucha** [comment]
Nice catch! I'll fix it and let you know.

**Comment by Tomucha** [comment]
Here you go:

https://pub.dev/packages/i69n
https://github.com/fnx-io/i69n/commit/e33846aa71d360c42f7fecb5253cbf3839a12b45#diff-2a454092e41d48e65566b276a042dcefafd086a347101ed534d60b72b1f6fc3aR51

Let me know in case it does't work as expected.

Thanks!

**Comment by StanislawNagorski** [comment]
Amazing thx!
